### ISSUE TITLE
Tracking issue for libstd/libredox compatibility.

### ISSUE THREAD

**Issue by Ticki** [redox-os/redox#572]
**Description**: This issue tracks the compatibility between Redox's libstd ("libredox") and the upstream libstd.

**List**:

- [x] Full IO compatibility. [Done](https://github.com/redox-os/redox/pull/552).
- [x] Moving extras to a seperate library. [Done](https://github.com/redox-os/extras).
- [ ] Full fs compatibility.
- [ ] Lacking sync primitives:
  - [x] Mutex.
  - [x] mpsc.
  - [ ] Barrier.
  - [ ] CondVar.
  - [x] Atomic types.
- [ ] Remove unnecessary reexports.
- [x] Collections:
  - [x] HashMap.
    - [x] SipHasher.
  - [x] HashSet
  - [x] BTreeMap.
  - [x] BTreeSet.
  - [x] Vec.
  - [x] VecDeque.
  - [x] LinkedList.
- [ ] Networking:
  - [x] CheckSum.
  - [x] IPv4.
  - [x] Ipv6.
  - [ ] Incoming.
  - [ ] TcpListener.
  - [ ] TcpStream.
  - [ ] UdpSocket.
  - [ ] LookupHost
- [ ] File management:
  - [x] File.
  - [x] canonicalize.
  - [x] create_dir.
  - [x] metadata.
  - [x] read_dir.
  - [x] remove_dir.
  - [x] remove_file.
  - [x] OpenOptions.
  - [ ] copy.
  - [ ] rename.
  - [ ] set_permissions.
  - [ ] soft_link.
  - [ ] hard_link.
  - [ ] read_link.
  - [ ] create_dir_all.
  - [ ] remove_dir_all.
  - [ ] Permissions.
  - [ ] DirBuilder.
- [ ] Time:
  - [x] Duration.
  - [x] Instant.
  - [x] SystemTime.
  - [ ] SytemTimeError.
- [ ] Threading:
  - [x] spawn.
  - [x] sleep.
  - [x] yield_now.
  - [x] .join().
  - [ ] park.
  - [ ] park_timeout.
  - [ ] panicking.
  - [ ] LocalKey.
  - [ ] Builder.
  - [ ] current.

**Comment by Ticki** [comment]
cc @Mouvedia.

**Comment by Mouvedia** [comment]
redox-os/extras doesn't exist. Should it be [redox-os/libextra](https://github.com/redox-os/libextra) instead?

**Comment by nounoursheureux** [comment]
`remove_file` and `remove_dir` exist but they are not compatible with libstd: [Rust](https://doc.rust-lang.org/nightly/std/fs/fn.remove_file.html) / [Redox](https://doc.redox-os.org/std/fs/fn.remove_file.html)

**Comment by Ticki** [comment]
Yeah.

**Comment by jackpot51** [comment]
I gotta say, this is pretty much exactly what I need to run through and make it all 1:1

Thanks

**Comment by jackpot51** [comment]
I fixed the `remove_file` `remove_dir` signatures

**Comment by nounoursheureux** [comment]
@Ticki you can check `copy`, `rename`, `var`, `set_var`, and `remove_var` :smile:

**Comment by Ticki** [comment]
Oh, yeah.

**Comment by Mouvedia** [comment]
isaacs/github#590

**Comment by Ticki** [comment]
Oh, you only need ability to edit the comment. I have checked them off already.
