### ISSUE TITLE
Epic: design documentation draft

### ISSUE THREAD

**Issue by vitiral** [redox-os/redox#882]
I'm making this issue to keep track of the documentation efforts around developing the initial design documents [here](https://github.com/redox-os/design). This is not in that repo because it spans more than just that repo.

- [ ] (@vitiral) rough draft of design documents
  - [X] [drivers ABI](https://redox-os.github.io/design/#artifacts/SPC-DRIVERS)
  - [ ] syscall ABI
  - [ ] schemes API
  - [ ] refactor to fit everything together in a reasonable way
  - [ ] provide high level summary
- [ ] (@jackpot51) do first-pass documentation of [syscall](https://github.com/redox-os/syscall), broken up into:
  - [ ] one sentance summary of all functions + structs + traits
  - [ ] one paragraph doc of all functions + structs + traits
  - [ ] one sentance summary of all constants
- [ ] (@jackpot51) fill in comments to redox-os/drivers#3
